"""Write a README.md preview in every folder that contains images, plus a root index.

Each folder README is the folder name as a heading, then every image as a thumbnail
that links to the full file. Thumbnails are small WebPs in .thumbs/<folder>/, so the
READMEs load quickly. The root README links to each folder README.

Thumbnails are only regenerated when their source image changes: .thumbs/manifest.json
records the git blob hash of each source. Images missing from disk (e.g. in CI's sparse
checkout) are read straight from git, so only changed images get downloaded.

READMEs and thumbnails this script made for images or folders that no longer exist
are removed.

Usage:
  pip install pillow
  python scripts/make_readmes.py
"""
import io
import json
import os
import subprocess
from collections import defaultdict
from urllib.parse import quote

IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.webp', '.gif'}
MARKER = '<!-- Generated by scripts/make_readmes.py; edits will be overwritten. -->'
THUMB_WIDTH = 800
THUMB_DIR = '.thumbs'
THUMB_EXT = '.webp'
THUMB_QUALITY = 80
MANIFEST = f'{THUMB_DIR}/manifest.json'


def git(*args, **kw):
    return subprocess.run(['git', *args], capture_output=True, check=True, **kw).stdout


def git_files(*args):
    return git('ls-files', *args, text=True).splitlines()


def list_images():
    """Return {path: blob hash} for every image, excluding dot-folders like .thumbs."""
    # Tracked + untracked (not ignored) files, minus ones deleted locally.
    deleted = set(git_files('--deleted'))
    files = [f for f in git_files('--cached', '--others', '--exclude-standard') if f not in deleted]
    images = [f for f in files if '/' in f and not f.startswith('.')
              and os.path.splitext(f)[1].lower() in IMAGE_EXTS]

    # Hash files on disk (catches local edits); fall back to the index for files that
    # aren't checked out, which is every image in CI's sparse checkout.
    on_disk = [f for f in images if os.path.exists(f)]
    hashes = dict(zip(on_disk, git('hash-object', '--stdin-paths', input='\n'.join(on_disk), text=True).split()))
    not_on_disk = [f for f in images if f not in hashes]
    if not_on_disk:
        for line in git_files('--stage', '--', *not_on_disk):
            meta, path = line.split('\t', 1)  # "<mode> <hash> <stage>\t<path>"
            hashes[path] = meta.split()[1]
    return files, hashes


def thumb_paths(images):
    """Map each image to .thumbs/<folder>/<name>_thumb.webp (keeping the extension on clashes)."""
    wanted = defaultdict(list)
    for path in images:
        folder, _, name = path.rpartition('/')
        wanted[f'{THUMB_DIR}/{folder}/{os.path.splitext(name)[0]}_thumb{THUMB_EXT}'].append(path)
    thumbs = {}
    for thumb, sources in wanted.items():
        for path in sources:
            folder, _, name = path.rpartition('/')
            thumbs[path] = thumb if len(sources) == 1 else f'{THUMB_DIR}/{folder}/{name.replace(".", "-")}_thumb{THUMB_EXT}'
    return thumbs


def read_image_bytes(path, blob):
    if os.path.exists(path):
        with open(path, 'rb') as f:
            return f.read()
    return git('cat-file', 'blob', blob)  # partial clone fetches just this blob


def make_thumb(data, dest):
    from PIL import Image
    with Image.open(io.BytesIO(data)) as im:
        im.draft('RGB', (THUMB_WIDTH, THUMB_WIDTH))  # fast JPEG downscale on decode
        im = im.convert('RGB')
        height = round(im.height * THUMB_WIDTH / im.width)
        im = im.resize((THUMB_WIDTH, height), Image.LANCZOS) if im.width > THUMB_WIDTH else im
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        im.save(dest, 'WEBP', quality=THUMB_QUALITY, method=6)  # method 6: slowest, smallest


def update_thumbs(hashes, thumbs):
    try:
        with open(MANIFEST, encoding='utf-8') as f:
            manifest = json.load(f)
    except (FileNotFoundError, ValueError):
        manifest = {}

    new_manifest = {}
    for path in sorted(hashes):
        thumb = thumbs[path]
        entry = {'source': hashes[path], 'thumb': thumb}
        if manifest.get(path) != entry or not os.path.exists(thumb):
            make_thumb(read_image_bytes(path, hashes[path]), thumb)
            print(f'thumbnail {thumb}')
        new_manifest[path] = entry

    # Remove thumbnails whose source image is gone.
    keep = {e['thumb'] for e in new_manifest.values()}
    for old in manifest.values():
        if old['thumb'] not in keep and os.path.exists(old['thumb']):
            os.remove(old['thumb'])
            print(f'removed {old["thumb"]}')

    content = json.dumps(new_manifest, indent=1, sort_keys=True) + '\n'
    write(MANIFEST, content, marker=False)


def main():
    files, hashes = list_images()
    thumbs = thumb_paths(hashes)
    update_thumbs(hashes, thumbs)

    folders = defaultdict(list)
    for path in hashes:
        folders[path.rpartition('/')[0]].append(path)

    for folder, paths in sorted(folders.items()):
        up = '../' * (folder.count('/') + 1)
        lines = [MARKER, '', f'# {folder.rsplit("/", 1)[-1]}', '']
        for path in sorted(paths, key=str.lower):
            name = path.rpartition('/')[2]
            href, src = quote(name), up + quote(thumbs[path])
            # The blank line makes each image its own paragraph, so GitHub shows one per line.
            lines += [f'<a href="{href}"><img src="{src}" alt="{name}" title="{name}" width="{THUMB_WIDTH}"></a>', '']
        write(f'{folder}/README.md', '\n'.join(lines).rstrip() + '\n')

    # Root README: one link per folder preview.
    top = git('rev-parse', '--show-toplevel', text=True)
    lines = [MARKER, '', f'# {os.path.basename(top.strip())}', '']
    for folder, paths in sorted(folders.items()):
        count = f'{len(paths)} image{"s" if len(paths) != 1 else ""}'
        lines.append(f'- [{folder}]({quote(folder)}/README.md) ({count})')
    lines += [
        '',
        '## All wallpapers in one folder',
        '',
        'To point a slideshow (e.g. Windows\' Personalize > Background > Slideshow) at a single',
        'folder, run this once after cloning:',
        '',
        '```',
        'python scripts/flatten.py --install-hooks',
        '```',
        '',
        'It builds `all/`, a gitignored folder of hard links to every wallpaper (no extra disk',
        'space), and installs git hooks that rebuild it after each pull, checkout or rebase.',
    ]
    write('README.md', '\n'.join(lines) + '\n')

    # Remove generated READMEs from folders that no longer contain images.
    for f in files:
        folder, _, name = f.rpartition('/')
        if name == 'README.md' and folder and folder not in folders and os.path.exists(f):
            with open(f, encoding='utf-8') as fh:
                if fh.readline().strip() == MARKER:
                    os.remove(f)
                    print(f'removed {f}')


def write(path, content, marker=True):
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            old = f.read()
        if old == content:
            return
        if marker and not old.startswith(MARKER):
            print(f'skipped {path} (hand-written README, not overwriting)')
            return
    # In CI's sparse checkout, image folders may not exist on disk yet.
    if os.path.dirname(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print(f'wrote {path}')


if __name__ == '__main__':
    main()
