"""Write a README.md preview in every folder that contains images.

Each README is the folder name as a heading, then every image as a thumbnail that
links to the full file. READMEs this script wrote for folders that no longer have
images are removed.

Usage:
  python scripts/make_readmes.py
"""
import os
import subprocess
from collections import defaultdict
from urllib.parse import quote

IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.webp', '.gif'}
MARKER = '<!-- Generated by scripts/make_readmes.py; edits will be overwritten. -->'
THUMB_WIDTH = 400


def git_files(*args):
    return subprocess.run(['git', 'ls-files', *args], capture_output=True, text=True, check=True).stdout.splitlines()


def main():
    # Tracked + untracked (not ignored) files, minus ones deleted locally.
    deleted = set(git_files('--deleted'))
    files = [f for f in git_files('--cached', '--others', '--exclude-standard') if f not in deleted]

    folders = defaultdict(list)
    for f in files:
        folder, _, name = f.rpartition('/')
        if folder and os.path.splitext(name)[1].lower() in IMAGE_EXTS:
            folders[folder].append(name)

    for folder, names in sorted(folders.items()):
        lines = [MARKER, '', f'# {folder.rsplit("/", 1)[-1]}', '']
        for name in sorted(names, key=str.lower):
            url = quote(name)
            lines.append(f'<a href="{url}"><img src="{url}" alt="{name}" title="{name}" width="{THUMB_WIDTH}"></a>')
        write(f'{folder}/README.md', '\n'.join(lines) + '\n')

    # Remove generated READMEs from folders that no longer contain images.
    for f in files:
        folder, _, name = f.rpartition('/')
        if name == 'README.md' and folder not in folders and os.path.exists(f):
            with open(f, encoding='utf-8') as fh:
                if fh.readline().strip() == MARKER:
                    os.remove(f)
                    print(f'removed {f}')


def write(path, content):
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            old = f.read()
        if old == content:
            return
        if not old.startswith(MARKER):
            print(f'skipped {path} (hand-written README, not overwriting)')
            return
    # In CI's sparse checkout, image folders may not exist on disk yet.
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print(f'wrote {path}')


if __name__ == '__main__':
    main()
